name: Sync Supabase Schema

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Grab the code
        uses: actions/checkout@v4

      - name: Set up Supabase
        uses: supabase/setup-cli@v2
        with:
          version: latest

      - name: Update Database
        run: |
          supabase db query \
            --db-url "postgresql://postgres.${{ secrets.SUPABASE_PROJECT_REF }}:${{ secrets.SUPABASE_DB_PASSWORD }}@aws-0-ap-south-1.pooler.supabase.com:6543/postgres" \
            --file ./supabase/schema.sql