name: Sync Supabase Schema

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Grab the code
        uses: actions/checkout@v4

      - name: Set up Supabase
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Update Database
        run: |
          supabase db execute --project-ref ${{ secrets.Supabase_Project_Ref }} --password ${{ secrets.Supabase_DB_Password }} --file ./supabase/schema.sql